name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  ci:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 10
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
