name: Linter

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install dependencies
        run: npm install
      - name: Run linter
        run: npm run eslint
